services:
  # Web service
  - type: web
    name: shopify-sku-replacement
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET_KEY
        sync: false
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: SHOP_URL
        sync: false
      - key: HOST
        sync: false

# Note: We're using MongoDB Atlas instead of Render's database
# See mongodb-atlas-setup.md for instructions
